const config = {
  popOverStyles: {
    topRight: 'arrow-top-right',
    topLeft: 'arrow-top-left',
    topCenter: 'arrow-top-center',
    bottomRight: 'arrow-bottom-right',
    bottomLeft: 'arrow-bottom-left',
    bottomCenter: 'arrow-bottom-center',
    leftTop: 'arrow-left-top',
    leftCenter: 'arrow-left-center',
    leftBottom: 'arrow-left-bottom',
    rightTop: 'arrow-right-top',
    rightCenter: 'arrow-right-center',
    rightBottom: 'arrow-right-bottom',
    default: 'arrow-bottom-right',
  },
  left: {
    topCenter: '-50%',
    topRight: '-90.9%',
    topLeft: '-10%',
    bottomCenter: '-50%',
    bottomRight: '-90.9%',
    bottomLeft: '-10%',
    leftTop: '5%',
    leftCenter: '5%',
    leftBottom: '5%',
    rightTop: '-105%',
    rightCenter: '-105%',
    rightBottom: '-105%',
  },
  top: {
    topLeft: '10%',
    topCenter: '10%',
    topRight: '10%',
    bottomRight: '-110%',
    bottomLeft: '-110%',
    bottomCenter: '-110%',
    leftTop: '-10%',
    leftCenter: '0',
    leftBottom: '-50%',
    rightTop: '-10%',
    rightCenter: '0',
    rightBottom: '-50%',
    default: '-100%',
  },
  warnings: {
    missingContent: 'Write some children elements to render content in the Popover',
  }
};

export const Arrows = [
  'topLeft',
  'topCenter',
  'topRight',
  'leftTop',
  'leftCenter',
  'leftBottom',
  'rightTop',
  'rightCenter',
  'rightBottom',
  'bottomLeft',
  'bottomCenter',
  'bottomRight',
];

export default config;
